"""Season-scoped city -> franchise overrides.

`city_franchise_map.csv` (generated by reconcile.py) maps a city to ONE
franchise, so it is era-blind by construction. Where two franchises hold the
same city in different eras (Manatí: Atenienses 2015-16, Osos 2023+) the map
alone is wrong for one of them.

`city_franchise_season_overrides.csv` is the hand-maintained refinement. It is
not generated, so `make reconcile` never rewrites it. Both resolvers that read
the city map (`build_web_data._team_resolver`, `parse_players._load_club_resolver`)
go through this module, so they cannot disagree about an era.

Only add a row the archive supports: a season range is the seasons actually
observed, not a franchise's founding or dissolution year.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Callable

OVERRIDES_FILE = "city_franchise_season_overrides.csv"
_COLUMNS = ("city", "season_start", "season_end", "franchise_id", "evidence")

# normalized city -> [(season_start, season_end or None for open-ended, franchise_id)]
Overrides = dict[str, list[tuple[int, int | None, str]]]


def load_overrides(path: Path, norm: Callable[[str], str]) -> Overrides:
    """Parse and validate the overrides file. `norm` is the caller's own city
    normalizer, so keys line up with however that caller normalizes lookups.

    Raises ValueError on a malformed row or on overlapping ranges for one city:
    a silent tie-break would put the wrong franchise on a season."""
    out: Overrides = {}
    with path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        missing = [c for c in _COLUMNS if c not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"{path.name}: missing columns {missing}")
        for line_no, r in enumerate(reader, start=2):
            where = f"{path.name}:{line_no}"
            city = norm(r["city"] or "")
            fid = (r["franchise_id"] or "").strip()
            # PC3: a row without provenance does not get written.
            if not city or not fid or not (r["evidence"] or "").strip():
                raise ValueError(f"{where}: city, franchise_id and evidence are required")
            start, end = (r["season_start"] or "").strip(), (r["season_end"] or "").strip()
            if not start.isdigit() or (end and not end.isdigit()):
                raise ValueError(f"{where}: season_start/season_end must be years "
                                 f"(season_end may be blank for open-ended), got {start!r}/{end!r}")
            lo, hi = int(start), (int(end) if end else None)
            if hi is not None and hi < lo:
                raise ValueError(f"{where}: season_end {hi} is before season_start {lo}")
            out.setdefault(city, []).append((lo, hi, fid))

    for city, spans in out.items():
        spans.sort(key=lambda s: s[0])
        for (_, prev_hi, _), (next_lo, _, _) in zip(spans, spans[1:]):
            if prev_hi is None or prev_hi >= next_lo:
                raise ValueError(f"{path.name}: overlapping season ranges for {city!r}")
    return out


def _year(season: int | str | None) -> int | None:
    if isinstance(season, int):
        return season
    s = (season or "").strip()
    return int(s) if s.isdigit() else None


def override_for(overrides: Overrides, city_key: str, season: int | str | None) -> str | None:
    """franchise_id for an already-normalized city in `season`, else None.

    A missing or non-year season ("unknown", a split-year label) never matches,
    so the caller falls back to the era-blind map exactly as before."""
    year = _year(season)
    if year is None:
        return None
    for lo, hi, fid in overrides.get(city_key, ()):
        if lo <= year and (hi is None or year <= hi):
            return fid
    return None
